### PR TITLE
Use trapezoidal window in CTF

### PR DESCRIPTION
**Pull request by noraderam**
A follow-up to #51, after discussion with @eric-jones.

A [`tukey` window](http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.tukey.html) is probably what we want to use here, but that's not available in the version of `scipy` we're currently using.

### CODE REVIEW

**Comment by dmsurti** [comment]
@noraderam Tested from the app also. 

LGTM.

**Comment by noraderam** [comment]
@jwiggins Any objections? I'm going to make a minor release after this goes in

**Comment by jwiggins** [comment]
In principle no. What's the desired effect? A "thick" isosurface?

IIRC you could only get thin surfaces with the previous implementations, right?

**Comment by noraderam** [comment]
> What's the desired effect? A "thick" isosurface?
> 
> IIRC you could only get thin surfaces with the previous implementations, right?

The goal is to have rectangles of constant opacity which can be made as thin as possible and made to abut directly against each other

**Comment by jwiggins** [comment]
Ahh, I see. This certainly does the trick.

Have you thought about supporting more than one window shape simultaneously? I haven't looked at a known volume yet with this change, so take that question with a grain of salt. It _might_ be desirable to have multiple windows, despite the implementation burden.

**Comment by noraderam** [comment]
> It might be desirable to have multiple windows, despite the implementation burden.

I can see how that might be useful to the user. The main pain point would be serialization and deserialization, I think, but it wouldn't be all that complicated. It's certainly something to consider for later work.

**Comment by jwiggins** [comment]
I'm fine with this going in now, but I'm going to start working on multiple window support. :wink: I have an idea how it can be deserialized without too much trouble. Not sure about serialization, but we'll see.

**Comment by noraderam** [comment]
Sounds good, thanks!


With @jwiggins and @dmsurti signing off, I'm going to go ahead and merge.

**Pull request merged**
