### PR TITLE
Use new mayavi

### PR DESCRIPTION
**Pull request by prabhuramachandran**
Changes to ensemble to use the latest mayavi from master.   This cleans up the code a bit and uses the volume module from upstream instead of having local changes.

### CODE REVIEW

**Comment by jwiggins** [comment]
This looks nice, but I want to see if I can fix `traits_enaml` so that it tests correctly.

**Comment by prabhuramachandran** [comment]
Sounds good, might be good to port the code so it works on Python2 and 3 at some point.  Should I take a stab?

**Comment by jwiggins** [comment]
That would be great!

**Comment by jwiggins** [comment]
The `traits_enaml` breakage is fixed. That should make it a bit easier to concentrate on what's actually being changed here.

**Comment by prabhuramachandran** [comment]
This fails because an ancient VTK version is installed which will not work with mayavi master.  If you just `pip install vtk` you should get 8.1.1 which might work better, otherwise we need to get version 7.x or so from edm.  The issue with all these is that VTK 7.x and above need OpenGL 3.2 or so which the default travis nodes do not seem to have?

**Comment by rahulporuri** [comment]
@jwiggins Do you have any suggestions on how we can workaround the issue that @prabhuramachandran mentioned in the earlier comment?

> The issue with all these is that VTK 7.x and above need OpenGL 3.2 or so which the default travis nodes do not seem to have?

The testsuite is very small and it doesn't take too long to run locally. Would you be okay with running the test suites locally instead of on CI? We already have an `etstool.py` utility on master (not on this branch), which can be used to install/test the package on multiple runtimes with one command.

The long term solutions are :

- use a VTK egg with mesa support
- use custom docker images with the necessary version of OpenGL.

**Comment by jwiggins** [comment]
I don't have any problem with using a skip decorator to disable GL-needing tests on Travis.

Long term, I like the idea of a docker image with the right pre-reqs. Can Travis use arbitrary docker images?

**Comment by rahulporuri** [comment]
> Long term, I like the idea of a docker image with the right pre-reqs. Can Travis use arbitrary docker images?

Maybe not. After Googling a little, I have come across a few issues that request the feature and compare it to a similar feature on GitLab. E.g. https://github.com/travis-ci/travis-ci/issues/7726

**Comment by jwiggins** [comment]
Thanks for keeping after this!

(CircleCI can use arbitrary docker images)

**Comment by rahulporuri** [comment]
Thanks @prabhuramachandran @jwiggins

**Pull request merged**
