### PR TITLE
Recalculate volume min and max when raw data changes

### PR DESCRIPTION
**Pull request by noraderam**
`vmin` and `vmax` should be recalculated whenever `VolumeRenderer.data.raw_data` changes. It's not sufficient to update when `data` itself changes.

### CODE REVIEW

**Comment by jwiggins** [comment]
Other than the build failure, LGTM.

**Comment by pberkes** [comment]
Merging master should solve the CI issues. A test would be nice?

**Comment by noraderam** [comment]
@pberkes: I'll see what I can do about adding a test, hopefully next week

**Comment by noraderam** [comment]
@pberkes Rather late, but a test has been added!

**Comment by jwiggins** [comment]
:+1:

**Comment by pberkes** [comment]
Thank you!

**Pull request merged**
