### PR TITLE
Make volume viewer compatible with VTK 5.10 and 6.x

### LINKED ISSUE #41: Volume Viewer is not compatible with VTK 6.x
For example: Volume Viewer on VTK 6.1 or 6.2 fails as such:

```
  File "/Users/deepaksurti/repos/git/ensemble/ensemble/volren/volume_data.py", line 49, in _resample_data
    output_spacing=output_spacing)
  File "tvtk_classes/image_reslice.py", line 64, in __init__
    tvtk_base.TVTKBase.__init__(self, vtk.vtkImageReslice, obj, update, **traits)
  File "/Users/deepaksurti/repos/git/mayavi/tvtk/tvtk_base.py", line 307, in __init__
    super(TVTKBase, self).__init__(**traits)
  File "/Users/deepaksurti/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_handlers.py", line 104, in _read_only
    name, class_of( object ) )
TraitError: The 'input' trait of an ImageReslice instance is 'read only'.
```

Fix the pipeline configuration so that it is backward compatible with 5.10 as well.

### PR DESCRIPTION
**Pull request by dmsurti**
Fixes #41.

This uses the `tvtk.common` API to ensure the Volume Viewer related VTK pipeline configuration is compatible with VTK 6.x and backwards compatible with 5.10 as well.

### CODE REVIEW

**Comment by jwiggins** [comment]
:+1: Looks like Travis is a bit unhappy though...

**Comment by dmsurti** [comment]
@jwiggins The `CTFEditor` related tests are failing `test_mouse_drag_alpha` and `test_mouse_drag_color`. The tests pass locally on OS X. Are the changes I made in any way related to CTFEditor?

**Comment by jwiggins** [comment]
No. In fact, the tests appear to be failing in the same way as they are in #40

**Comment by pberkes** [comment]
@dmsurti Can you please try and merge master now? The errors should disappear.

**Comment by dmsurti** [comment]
@pberkes Done. Travis is now happy!

**Comment by jwiggins** [comment]
Thanks Deepak!

**Pull request merged**
