### PR TITLE
test-new-cleaned-up-enable-setup

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by noraderam** [comment]
Well, shucks. I think it would be worthwhile to try to figure out what `pip` is doing. I'd like to know why it's running `setup.py` in `enable` at that point when it hasn't tried installing the other `dev_requirements.txt` packages yet--it looks like it's just collecting eggs initially.

**Comment by itziakos** [comment]
My current hypothesis is that the problem is still with enable.

**Comment by itziakos** [comment]
It looks that pip collects all the top level requirements and downloads them, the it tries to find their runtime and setup dependencies by importing the `setup.py` for each downloaded dependency. When it reaches enable it tries to import enable's setup.py but fails because the __version__ is import from kiva._version but `kiva/__init__.py` ends up at some point importing `numpy` and `traits`.

**Comment by jwiggins** [comment]
So, we should probably not get `__version__` from `kiva._version` then. Note that we discussed this in enthought/enable#166. I believe Corran's alternate suggestion there was to write a `_version.py` into both kiva and enable packages.

**Comment by itziakos** [comment]
I have update the enable PR to save two copies of the file one inside enable and one inside kiva, this should allow setup to finish importing

**Comment by jwiggins** [comment]
It makes it to tests now then fails. :tired_face:

**Comment by itziakos** [comment]
i think we can merge this to the travis-failure branch now. The test failures are probably not related to the package builds anymore.

**Comment by jwiggins** [comment]
Agreed.

**Pull request merged**
